---
  - name: Playbook
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: copy script to slave
        copy: src=j1.sh dest=/root mode=0777
      - name: Execute the script
        script: /root/j1.sh
